---
name: CI Build and Push

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  import-build-push:
    if: ${{ github.event.label.name == 'CI:TriggerBuild' }}
    uses: ${{ secrets.DOCKERHUB_USERNAME }}/ci-helpers/.github/workflows/build-push.yml@main
    with:
      app-name: "go-ethereum"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
